services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./packages/service-frontend/DockerFile
    ports: 
     - 3000:3000
    command: npm run dev
    volumes:
      - ./packages/service-frontend/node_modules:/app/node_modules
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./packages/service-backend/DockerFile
    ports: 
     - 4000:4000