services:
  docker-study-frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./packages/service-frontend/DockerFile
    ports: 
     - 3000:3000
    volumes:
      - ./packages/service-frontend/node_modules:/app/node_modules
  docker-study-backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./packages/service-backend/DockerFile
    ports: 
     - 4000:4000
  docker-study-server:
    container_name: server
    build:
      context: .
      dockerfile: ./packages/service-server/DockerFile
    ports: 
     - 80:80  
    volumes:
       - ./packages/service-server/nginx.conf:/etc/nginx/nginx.conf